defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

title: GitHub Pages Beispiel 
sass:
        sass_dir: _sass
        style: compressed

theme: jekyll-theme-cayman

